# Training
num_epochs: 100
batch_size: 512
learning_rate: 1e-5
eps: 1e-5
grad_clip: 100.0
max_steps_per_episode: 10000

# Behavior
gamma: 0.997            # Discount factor for the reward
discount_lambda: 0.95   # return mixing factor
imag_horizon: 16        # Horizon for imagined trajectories

# Simulation 
visualize: True
dt_simulation: 0.02

#Model
act: 'SiLU'             # Activation function
norm: True              # Layer Normalization
units: 32               # Number of neurons in each layer

# Training
save_dir: "saved_models"  # Directory to save trained models
log_dir: "runs"  # Directory for TensorBoard logs
save_frequency: 10  # Save models every N episodes (None to disable)

# Actor
actor:
  layers: 2
  dist: 'normal'
  entropy: 3e-4
  unimix_ratio: 0.01
  std: 'learned'
  min_std: 0.1
  max_std: 1.0
  temp: 0.1
  outscale: 1.0

# Critic
critic:
  layers: 2
  dist: 'symlog_disc'
  outscale: 0.0