training_config:
  act: SiLU
  actor:
    dist: normal
    entropy: 3e-4
    imag_grad: reinforce
    layers: 4
    max_std: 1.0
    min_std: 0.1
    outscale: 1.0
    std: learned
    temp: 0.1
    unimix_ratio: 0.01
  batch_length: 10
  batch_size: 16
  critic:
    dist: symlog_disc
    layers: 4
    outscale: 0.0
    slow_target: true
    slow_target_fraction: 0.02
    slow_target_update: 1
  deterministic_run: false
  device: cpu
  discount_lambda: 0.95
  dt_simulation: 0.02
  eps: 1e-5
  eval_episodes: 10
  eval_visualize: false
  final_eval_episodes: 10
  gamma: 0.997
  grad_clip: 100.0
  imag_horizon: 15
  learning_rate: 3e-3
  log_dir: runs
  max_steps_per_episode: 10000
  norm: true
  num_epochs: 10000
  reward_EMA: true
  save_dir: saved_models
  save_frequency: 1000
  seed: 42
  units: 512
  visualize: false
training_metadata:
  log_directory: runs\snn_actor_critic_20250708_115346
  save_directory: saved_models
  timestamp: '2025-07-08 11:53:46'
